# Generated by Django 5.0.6 on 2024-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='desig',
            field=models.CharField(default='user', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default='telidhu@gmail.com', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='teligu', max_length=50),
        ),
    ]
