# Generated by Django 5.0.6 on 2024-06-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_register_desig_alter_register_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
