# Generated by Django 5.1 on 2024-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_message_delete_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Phone',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
